spring.application.name=url-shortener

# ===============================
# MySQL
# ===============================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/url}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Redis
# ===============================

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.connect-timeout=500ms
spring.data.redis.timeout=500ms

# ===============================
# Server
# ===============================

server.port=${PORT:8080}

# ===============================
# Rate Limiter
# ===============================

rate.limit.shorten.max-requests=10
rate.limit.shorten.window-seconds=60

rate.limit.analytics.max-requests=10
rate.limit.analytics.window-seconds=60
